# Entorno Conda para Sistema de Gestión de Ejercicios
# Señales y Sistemas - PUC Chile

name: ejercicios-sys

channels:
  - conda-forge
  - defaults

dependencies:
  # Python base
  - python=3.11

  # Framework web principal
  - streamlit>=1.28.0

  # Manipulación de datos - disponibles en conda-forge
  - pandas>=2.0.0
  - numpy>=1.24.0

  # Visualización - disponibles en conda-forge
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0

  # Utilidades para archivos
  - pillow>=10.0.0

  # Procesamiento de fechas
  - python-dateutil>=2.8.0

  # Jupyter (útil para desarrollo y testing)
  - jupyter
  - ipykernel

  # Testing y desarrollo
  - pytest>=7.4.0
  - pytest-cov>=4.1.0

  # Formateo de código
  - black>=23.7.0
  - isort>=5.12.0

  # Type checking
  - mypy>=1.5.0

  # Dependencias via pip (no disponibles en conda-forge)
  - pip
  - pip:
    # Generación de documentos LaTeX
    - pylatex>=1.4.1
    - reportlab>=4.0.0
    
    # Parsing de documentos
    - PyPDF2>=3.0.0
    - python-docx>=0.8.11
    
    # Documentación
    - sphinx>=7.1.0
    - sphinx-rtd-theme>=1.3.0